# =================================================================
# Configuração do Prometheus para FIAP Cloud Games (FCG)
# Coleta de métricas da aplicação e infraestrutura
# =================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Configuração de alertas
rule_files:
  - "alert_rules.yml"

# Configuração do Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Jobs de coleta de métricas
scrape_configs:
  # === PROMETHEUS SELF-MONITORING ===
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 5s

  # === FGC API METRICS ===
  - job_name: 'fgc-api'
    static_configs:
      - targets: ['fgc-api:8080']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # === FGC API HEALTH CHECK ===
  - job_name: 'fgc-api-health'
    static_configs:
      - targets: ['fgc-api:8080']
    metrics_path: /health
    scrape_interval: 30s
    scrape_timeout: 10s

  # === SQL SERVER METRICS ===
  - job_name: 'sql-server'
    static_configs:
      - targets: ['fgc-db:1433']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # === DOCKER METRICS ===
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    metrics_path: /metrics
    scrape_interval: 30s

  # === NODE EXPORTER (Sistema) ===
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics
    scrape_interval: 15s

# # Configurações de retenção
# storage:
#   tsdb:
#     retention.time: 7d
#     retention.size: 1GB