# =================================================================
# Configuração do Datasource do Grafana
# Conecta o Grafana ao Prometheus
# =================================================================

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    version: 1
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: "POST"